In [1]:
path = "./PF08238_full_length_sequences.fasta"

In [18]:
from tape import datasets
from tape import TAPETokenizer
import torch
import numpy as np
import pandas as pd

In [3]:
dataset = datasets.dataset_factory(path)

In [5]:
tokenizer = TAPETokenizer(vocab='iupac') 
tokenizer

In [10]:
all_data =  [i['primary'] for i in dataset]
print_limit = 5
for i in range(len(all_data)):
    if i > print_limit:
        break
    else:
        print(all_data[i], "\n")

MHGFKTVLSALFGSVALLSFAGSAFALDPKTVVPIERAPGEVFSLGFKAYKRGEKLEAFEALRYAAEKGHAGARWKLGQMYAQGDGVPENDYEAFKIFEEIIAEDEDDTSSSPNAAYVASSVVALGDYMRTGIPGTPVSVDLPQARQLYFHAASIFGDPKAQFELGRMLLNGDGGRPNPRQAARWLKLSAEKGNTGAQALLGYLLFDGEKISLQAQPVRGLAMLTLALRHATEKDERWIRPLQEEVFSLASEGDRRTALAYAEEHQGTIAKN 

MHGFKTVLSALFGSVALLSFAGSAFALDPKTVVPIERAPGEVFSLGFKAYKRGEKLEAFEALRYAAEKGHAGARWKLGQMYAQGDGVPENDYEAFKIFEEIIAEDEDDTSSSPNAAYVASSVVALGDYMRTGIPGTPVSVDLPQARQLYFHAASIFGDPKAQFELGRMLLNGDGGRPNPRQAARWLKLSAEKGNTGAQALLGYLLFDGEKISLQAQPVRGLAMLTLALRHATEKDERWIRPLQEEVFSLASEGDRRTALAYAEEHQGTIAKN 

MVVPFAKFLPLINEIGNFFNETIELVEAAEHNNKRTCEILKNRVHVAELAVRELREKRKDREDFFNKINYIRLQELSIVIARIKKFISEISLMKTLIKYLKEKSVEKVFKELCGEFDVYINLLSFSINVEIADELEQLKSDQDDLFKYLQEMVAGIDDNDCFADSSKKFFSTIVKVNAMNNTMVHFTRGKFRSLTKINDIFQVHPLEFSDYESDDNEKTREYRRVYKWYKKTNKGAEFAFKLIYNRDDQMDLQSRIIILKELHDWQNIIKFYGIIYDGREWHFVNEWAEYGNLREFYQNKNDFDLKLKLRISLDIARGLNFLRIVEISHRDIRAENILITLNETAKLANFSSRYESASKSTLDKYRYYAPEVLDIYSFFNYDQRSEVYSFGILLWEIAEERIPHQGNNDIGDIIDKVRNKMYREPFSENNQMPEEFKQLEIEAVHHDPDF

In [12]:
max_ = 0
new_data = []
for i in all_data:
    if len(i) > max_:
        max_ = len(i)
    else:
        pass
print("Maximum length of sequence: ", max_)    

Maximum length of sequence:  3915


In [13]:
new_data = []
threshold = int(100)
for i in all_data:
    if len(i) < threshold:
        new_data.append(i)
print("After limiting maximum sequence length to 100, number of sequences: ", len(new_data))   

After limiting maximum sequence length to 100, number of sequences:  433


In [14]:
token_ids = [torch.tensor([tokenizer.encode(i)]) for i in new_data]
for i in range(len(token_ids)):
    if i > print_limit:
        break
    else:
        print(token_ids[i], "\n")

tensor([[ 2, 16, 23, 23, 19, 17, 17, 19, 17,  8, 28, 13, 17, 26, 15, 14, 15,  5,
          9, 17, 11,  8, 14, 13,  5, 16, 17, 17, 15,  5, 17,  7, 28, 14, 17, 25,
         11, 23,  9, 14, 17, 15,  9, 14,  5, 10, 28, 26, 28, 20, 14,  5,  5,  9,
         16, 14, 15, 21, 13,  3]]) 

tensor([[ 2, 16,  5, 28,  5,  8,  5, 15, 13,  9,  5, 19,  9,  5, 22, 15, 23, 17,
         14, 22,  5, 11,  9,  9, 13, 28, 21, 25, 11, 15, 16, 28, 22, 23, 11, 15,
         11, 25,  5, 25,  8, 28, 25,  5,  5, 12, 14, 26, 10, 17, 15,  5,  5, 15,
         14, 11, 25, 21,  8,  5, 21,  9, 20, 21, 21,  9, 16, 25,  8, 28, 16, 22,
         22, 15,  9, 15, 21, 20,  5, 20, 21,  5,  5, 21,  9, 26, 16, 20, 14,  5,
         12,  3]]) 

tensor([[ 2, 16,  5,  5,  9, 21, 11,  8,  5,  8,  5, 20,  5, 16, 15, 11,  5,  5,
         28, 12, 15, 11, 22, 11, 25, 19, 14,  8, 19, 25, 20,  5, 15,  5, 26, 15,
         20, 21, 11, 20,  5, 11, 11, 22,  5, 15,  5, 11, 21, 10, 15, 11, 19,  5,
         21,  5,  5, 15,  8, 11, 11, 25,  8, 12, 11

In [15]:
pads = datasets.pad_sequences(token_ids)
pads = pads.squeeze()
print(pads.shape)
pads

torch.Size([433, 101])


tensor([[ 2, 16, 23,  ...,  0,  0,  0],
        [ 2, 16,  5,  ...,  0,  0,  0],
        [ 2, 16,  5,  ...,  0,  0,  0],
        ...,
        [ 2, 16,  9,  ...,  0,  0,  0],
        [ 2, 16,  7,  ...,  0,  0,  0],
        [ 2, 16,  7,  ...,  0,  0,  0]])

In [22]:
series = pd.DataFrame(new_data, columns=["sequence"]).sequence.str.lower()
series.head()

0    mttpnnpndyinwlklaengdkiamnnlancyknvgteknlekafy...
1    mayadalieapeasltnksageeiyrvglmystglgvavdyvaahk...
2    maaergdadaqamlgaayhlgsgvpkdpvqalawlqrgqaggsala...
3         xglgllyfhgkgvplnyaealkyfqkaaekgwpdaqfqlgfmyy
4         xglgllyfhgkgvplnyaealkyfqkaaekgwpdaqfqlgfmyy
Name: sequence, dtype: object

In [24]:
min_len = series.str.len().min().astype(int) 
max_len = series.str.len().max().astype(int) 
print(max_len, min_len)

99 37


In [29]:
from model import build_data
train_x, train_y, test_x, test_y = build_data(series, min_len = min_len, max_len = max_len)
max_index = int(max(train_x.max(), test_x.max()))

In [16]:
# Creating dataset tuples for training

training_data = np.empty((0,2))
#training_data = []

window = int(10)
for sentence in pads:
    sent_len = len(sentence)
    for i, word in enumerate(sentence):
        w_context = []
        if sentence[i] != 0:
            w_target = sentence[i]
            for j in range(i-window, i + window + 1):
                if j != i and j <= sent_len -1 and j >=0 and sentence[j]!=0:
                    w_context = sentence[j]
                    training_data = np.append(training_data, [[w_target, w_context]], axis=0)

print(len(training_data))
print(training_data.shape)
print(training_data[0:21])

674550
(674550, 2)
[[ 2. 16.]
 [ 2. 23.]
 [ 2. 23.]
 [ 2. 19.]
 [ 2. 17.]
 [ 2. 17.]
 [ 2. 19.]
 [ 2. 17.]
 [ 2.  8.]
 [ 2. 28.]
 [16.  2.]
 [16. 23.]
 [16. 23.]
 [16. 19.]
 [16. 17.]
 [16. 17.]
 [16. 19.]
 [16. 17.]
 [16.  8.]
 [16. 28.]
 [16. 13.]]


In [17]:
with open('training_data_new_fasta.npy', 'wb') as f:
    np.save(f, training_data)